=== Marina2611/PHP/src/main/resources/xml/adressen.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT Adressen (Adresse)*>
<!ELEMENT Adresse (Nummer,Vorname, Nachname,Strasse,Postleitzahl, Ort)>
<!ELEMENT Vorname (#PCDATA)>
<!ELEMENT Nachname (#PCDATA)>
<!ELEMENT Strasse (#PCDATA)>
<!ELEMENT Postleitzahl (#PCDATA)>
<!ELEMENT Ort (#PCDATA)>
<!ELEMENT Nummer (#PCDATA)>

=== Marina2611/PHP/src/main/resources/xml/adressen.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Adressen SYSTEM "adressen.dtd">
<Adressen>
    <Adresse>
        <Nummer>1</Nummer>
        <Vorname>Max</Vorname>
        <Nachname>Mustermann</Nachname>
        <Strasse>Mittelstrasse 2</Strasse>
        <Postleitzahl>32657</Postleitzahl>
        <Ort>Lemgo</Ort>
    </Adresse>
    <Adresse>
        <Nummer>2</Nummer>
        <Vorname>Eva</Vorname>
        <Nachname>Musterfrau</Nachname>
        <Strasse>Hauptstrasse 1</Strasse>
        <Postleitzahl>32756</Postleitzahl>
        <Ort>Detmold</Ort>
    </Adresse>
</Adressen>
